version: '3'

services:
  client:
    build: .
    ports:
      - 4012:4012
    restart: always
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  volumes:
    mongo-data: