version: '3'

services:
  client:
    container_name: photo-gallery-service
    build: .
    ports:
      - 4012:4012
    restart: always
    depends_on:
      - server
    stdin_open: true
    tty: true
    logging:
      driver: "none"

  server:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: "none"

volumes:
  mongo-data:
